"""Render a :class:`WeekContext` into the week-in-review DRAFT markdown (#38).

Seven sections, mirroring the one-off ``WEEK-IN-REVIEW-2026-05-22-to-25``
template:

    Arc · Per-repo commits · Decisions locked · Patterns stolen ·
    Next-week candidates · By the numbers · Honest reflection

Everything is mechanical aggregation EXCEPT "Decisions locked" and
"Honest reflection", which are synthesised by a LOCAL Ollama model. Both
degrade gracefully: if the model is unreachable (``client is None``) or a
call fails mid-run, the section renders a deterministic fallback carrying
a ``[LLM unavailable]`` marker so the mechanical data is never lost (the
operator can re-run once Ollama is back). The file always carries a
``status: DRAFT`` banner — the routine never auto-publishes.

Synthesis runs LOCAL only (CLAUDE.md #no-mnpi-to-cloud — was cited as §5.4) —
no internal context leaves the machine.
"""

from __future__ import annotations

import logging

from routines.shared.ollama_client import OllamaError
from routines.shared.vault_writer import atomic_write
from routines.week_in_review.collect import WeekContext

log = logging.getLogger(__name__)

DEFAULT_MODEL = "qwen3:14b"
LLM_UNAVAILABLE = "[LLM unavailable]"
COMMIT_DISPLAY_CAP = 20

# Exact section headers — the render test asserts all seven are present.
SECTIONS = (
    "## Arc",
    "## Per-repo commits",
    "## Decisions locked",
    "## Patterns stolen",
    "## Next-week candidates",
    "## By the numbers",
    "## Honest reflection",
)


# ── Output path + writer (idempotent) ──────────────────────────────────────


def review_path(vault_root, label: str):
    """``<vault>/Resources/Week-in-Review/<YYYY-Www>.md``."""
    from pathlib import Path
    return Path(vault_root) / "Resources" / "Week-in-Review" / f"{label}.md"


def write_review(vault_root, label: str, markdown: str):
    """Atomic-write the draft, overwriting any prior draft for the same week
    (a draft, not append-only). Returns the absolute path."""
    path = review_path(vault_root, label)
    atomic_write(path, markdown, vault_root=vault_root)
    return path


# ── Top-level render ───────────────────────────────────────────────────────


def render_markdown(
    ctx: WeekContext, *, client=None, model: str = DEFAULT_MODEL,
) -> str:
    """Compose the full DRAFT markdown. ``client`` is an
    :class:`OllamaClient` (or None to force the deterministic fallback for
    the two synthesised sections)."""
    decisions = synth_decisions_locked(ctx, client=client, model=model)
    reflection = synth_honest_reflection(ctx, client=client, model=model)

    parts = [
        _frontmatter(ctx),
        _banner(ctx),
        _arc(ctx),
        _per_repo(ctx),
        f"## Decisions locked\n\n{decisions}\n",
        _patterns(ctx),
        _next_week(ctx),
        _by_the_numbers(ctx),
        "## Honest reflection\n\n<!-- LLM-drafted; edit liberally -->\n\n"
        f"{reflection}\n",
    ]
    return "\n".join(parts)


# ── Mechanical sections ────────────────────────────────────────────────────


def _frontmatter(ctx: WeekContext) -> str:
    last_day = ctx.last_included_day.isoformat()
    return (
        "---\n"
        "type: week-in-review\n"
        "status: DRAFT\n"
        "sensitivity: internal\n"
        f"week: {ctx.label}\n"
        f"window: {ctx.start.isoformat()} to {last_day}\n"
        f"generated: {ctx.generated_at} · routines.week_in_review\n"
        "tags: [week-in-review, routines, auto-generated, draft]\n"
        "---\n"
    )


def _banner(ctx: WeekContext) -> str:
    last_day = ctx.last_included_day.isoformat()
    return (
        "## Status: DRAFT — operator review required\n\n"
        f"> Generated by `routines.week_in_review` on {ctx.generated_at}. "
        "Review, edit, remove this banner, then commit.\n\n"
        f"# Week in review — {ctx.start.isoformat()} to {last_day}  ({ctx.label})\n"
    )


def _arc(ctx: WeekContext) -> str:
    if not (ctx.total_commits or ctx.shipped or ctx.total_fires):
        return "## Arc\n\n_Quiet week — no commits, no items shipped, no routine fires._\n"
    shipped_n = len(ctx.shipped)
    bits = [
        f"{ctx.total_commits} commit{_s(ctx.total_commits)} across "
        f"{ctx.active_repos} repo{_s(ctx.active_repos)}",
        f"{shipped_n} item{_s(shipped_n)} shipped",
        f"{ctx.total_fires} routine fire{_s(ctx.total_fires)} "
        f"({ctx.total_errors} error{_s(ctx.total_errors)})",
    ]
    if ctx.telemetry.cost_usd:
        bits.append(f"${ctx.telemetry.cost_usd:.2f} local/cloud LLM spend")
    return "## Arc\n\n" + " · ".join(bits) + ".\n"


def _per_repo(ctx: WeekContext) -> str:
    lines = ["## Per-repo commits", ""]
    active = [r for r in ctx.repos if r.count]
    if not active:
        lines.append("_No commits in the window._")
        return "\n".join(lines) + "\n"
    for repo in active:
        lines.append(f"### {repo.repo} — {repo.count} commit{_s(repo.count)}")
        lines.append("")
        lines.append("| Hash | Date | Subject |")
        lines.append("| --- | --- | --- |")
        for c in repo.commits[:COMMIT_DISPLAY_CAP]:
            lines.append(f"| `{c.short_hash}` | {c.date} | {_cell(c.subject)} |")
        overflow = repo.count - COMMIT_DISPLAY_CAP
        if overflow > 0:
            lines.append("")
            lines.append(f"_+{overflow} more_")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _patterns(ctx: WeekContext) -> str:
    lines = ["## Patterns stolen", ""]
    if not ctx.patterns_stolen:
        lines.append("_None surfaced this week._")
        return "\n".join(lines) + "\n"
    for p in ctx.patterns_stolen:
        lines.append(f"- {_cell(p)}")
    return "\n".join(lines) + "\n"


def _next_week(ctx: WeekContext) -> str:
    lines = ["## Next-week candidates", ""]
    if not ctx.next_week:
        lines.append("_No open OUTSTANDING items found._")
        return "\n".join(lines) + "\n"
    lines.append("| Item | Priority | Owner | Effort | Title |")
    lines.append("| --- | --- | --- | --- | --- |")
    for c in ctx.next_week:
        lines.append(
            f"| {c.number} | {c.priority or '—'} | {_cell(c.owner) or '—'} "
            f"| {_cell(c.effort) or '—'} | {_cell(c.title)} |"
        )
    return "\n".join(lines) + "\n"


_SHIPPED_INLINE_CAP = 15


def _by_the_numbers(ctx: WeekContext) -> str:
    t = ctx.telemetry
    nums = [s.number for s in ctx.shipped]
    if len(nums) > _SHIPPED_INLINE_CAP:
        shipped_nums = ", ".join(nums[:_SHIPPED_INLINE_CAP]) + f", +{len(nums) - _SHIPPED_INLINE_CAP} more"
    else:
        shipped_nums = ", ".join(nums) or "none"
    busiest = max(ctx.routines, key=lambda r: r.total, default=None)
    busiest_txt = (
        f" — busiest: {busiest.routine} ({busiest.total})" if busiest else ""
    )
    top_spend = ""
    if t.top_spend:
        top = t.top_spend[0]
        top_spend = f" · top: {top.name} (${top.cost_usd:.2f})"
    lines = [
        "## By the numbers",
        "",
        f"- **Commits:** {ctx.total_commits} across {ctx.active_repos} "
        f"repo{_s(ctx.active_repos)}",
        f"- **Items shipped:** {len(ctx.shipped)} ({shipped_nums})",
        f"- **Routine fires:** {ctx.total_fires} ({ctx.total_errors} "
        f"error{_s(ctx.total_errors)}){busiest_txt}",
        f"- **LLM telemetry:** {t.calls} call{_s(t.calls)} · "
        f"{t.tokens_in:,} in / {t.tokens_out:,} out tokens · "
        f"${t.cost_usd:.2f}{top_spend}",
    ]
    return "\n".join(lines) + "\n"


# ── LLM sections (local Ollama) + deterministic fallbacks ──────────────────

_DECISIONS_SYSTEM = """\
You summarise the load-bearing engineering decisions a solo operator's
platform locked in this week. You are given: commit subjects, items moved
to the shipped archive, and any ADOPTED-CONVENTIONS / decisions added to
the tracked docs.

Return 3-7 markdown bullet points. Each bullet names ONE concrete decision
that is now load-bearing (e.g. an architecture choice, a new contract/flag,
a convention adopted) and, in a clause, why it matters. en-GB spelling.
Direct, factual, no celebration. If the evidence is thin, return fewer
bullets — do not invent decisions. Output ONLY the bullet list.
"""

_REFLECTION_SYSTEM = """\
You write the "Honest reflection" for a solo operator's weekly engineering
review. You are given mechanical facts about the week: commits, shipped
items, routine fires + errors, and LLM spend.

Write 4-8 sentences of plain prose (no bullets, no headings) naming the
real friction of the week — where effort went, what slipped, what error
rates or parallel-work collisions suggest. en-GB spelling. Direct and
self-critical; name specific incidents over generalities. No celebration,
no marketing language. If the week was quiet, say so plainly. Output ONLY
the prose.
"""


def _llm_context(ctx: WeekContext) -> str:
    subjects = ctx.all_subjects[:60]
    shipped = [f"{s.number} {s.title}" for s in ctx.shipped]
    signals = [f"({d.source}) {d.text}" for d in ctx.decision_signals]
    last_day = ctx.last_included_day.isoformat()
    return (
        f"Window: {ctx.start.isoformat()} to {last_day} ({ctx.label})\n\n"
        f"Commits ({ctx.total_commits} across {ctx.active_repos} repos):\n"
        + ("\n".join(f"- {s}" for s in subjects) or "(none)")
        + "\n\nItems shipped this week:\n"
        + ("\n".join(f"- {s}" for s in shipped) or "(none)")
        + "\n\nConventions / decisions added to docs:\n"
        + ("\n".join(f"- {s}" for s in signals) or "(none)")
        + "\n\nRoutine fires: "
        + f"{ctx.total_fires} ({ctx.total_errors} errors). "
        + f"LLM spend: ${ctx.telemetry.cost_usd:.2f}.\n"
    )


def synth_decisions_locked(ctx: WeekContext, *, client=None, model: str = DEFAULT_MODEL) -> str:
    if client is None:
        return _fallback_decisions(ctx)
    try:
        resp = client.chat(model=model, prompt=_llm_context(ctx), system=_DECISIONS_SYSTEM)
    except OllamaError as e:
        log.warning("week-in-review: decisions_locked LLM call failed: %s", e)
        return _fallback_decisions(ctx)
    except Exception as e:  # noqa: BLE001 — never crash the routine on the LLM
        log.warning("week-in-review: decisions_locked unexpected failure: %s", e)
        return _fallback_decisions(ctx)
    return (resp.content or "").strip() or _fallback_decisions(ctx)


def synth_honest_reflection(ctx: WeekContext, *, client=None, model: str = DEFAULT_MODEL) -> str:
    if client is None:
        return _fallback_reflection(ctx)
    try:
        resp = client.chat(model=model, prompt=_llm_context(ctx), system=_REFLECTION_SYSTEM)
    except OllamaError as e:
        log.warning("week-in-review: honest_reflection LLM call failed: %s", e)
        return _fallback_reflection(ctx)
    except Exception as e:  # noqa: BLE001
        log.warning("week-in-review: honest_reflection unexpected failure: %s", e)
        return _fallback_reflection(ctx)
    return (resp.content or "").strip() or _fallback_reflection(ctx)


def _fallback_decisions(ctx: WeekContext) -> str:
    """Deterministic stand-in: the marker + the raw mechanical signals so no
    data is lost while the model is down."""
    lines = [f"_{LLM_UNAVAILABLE} — Decisions locked not synthesised; raw signals below._", ""]
    if ctx.decision_signals:
        for d in ctx.decision_signals:
            lines.append(f"- {_cell(d.text)} _({d.source})_")
    elif ctx.shipped:
        for s in ctx.shipped:
            lines.append(f"- Shipped {s.number}: {_cell(s.title)}")
    else:
        lines.append("- _No mechanical decision signals found in the window._")
    return "\n".join(lines)


def _fallback_reflection(ctx: WeekContext) -> str:
    """Deterministic stand-in: the marker + a one-line mechanical summary."""
    if not (ctx.total_commits or ctx.shipped or ctx.total_fires):
        summary = "Quiet week — nothing landed and no routines fired."
    else:
        summary = (
            f"{ctx.total_commits} commits and {len(ctx.shipped)} shipped item(s) "
            f"across {ctx.active_repos} repo(s); "
            f"{ctx.total_errors} routine error(s) of {ctx.total_fires} fire(s)."
        )
    return f"_{LLM_UNAVAILABLE} — Honest reflection not synthesised._\n\n{summary}"


# ── helpers ────────────────────────────────────────────────────────────────


def _s(n: int) -> str:
    return "" if n == 1 else "s"


def _cell(text: str) -> str:
    """Make a string safe for a single markdown table cell: collapse
    newlines and escape pipes."""
    return (text or "").replace("\n", " ").replace("\r", " ").replace("|", "\\|").strip()
