"""Generate auto-built view files (BD.md, People.md) for each sector.

Plan v3 §6.9 Phase 4 + 5. Deterministic; no LLM.

- `BD.md` view: scan `Companies/*.md` for any with `sector:` matching
  target slug AND `bd_state` set. Render as table.
- `People.md` view: scan `People/*.md` for any with `sectors:` list
  containing target slug. Render grouped by role (operators / advisors /
  regulators).
- `_Index.md` regeneration: out of scope for Phase 4 v1 — operator
  edits manually. Future enhancement.
"""

from __future__ import annotations

import logging
import re
from datetime import date as date_cls
from pathlib import Path

import frontmatter

from routines.sectors.schema import slugify_sector
from routines.shared.vault_writer import atomic_write

log = logging.getLogger(__name__)


def regenerate_bd_view(vault_root: Path, sector: str) -> Path:
    """Walk Companies/ and rebuild Sectors/<sector>/BD.md."""
    target_slug = slugify_sector(sector)
    companies = _scan_companies(vault_root, target_slug)

    target_file = vault_root / "Sectors" / target_slug / "BD.md"
    if not target_file.parent.exists():
        log.warning("views: sector dir %s doesn't exist; skipping BD view", target_file.parent)
        return target_file

    body = _render_bd_view(target_slug, companies)
    atomic_write(target_file, body, vault_root=vault_root)
    return target_file


def regenerate_people_view(vault_root: Path, sector: str) -> Path:
    """Walk People/ and rebuild Sectors/<sector>/People.md."""
    target_slug = slugify_sector(sector)
    people = _scan_people(vault_root, target_slug)

    target_file = vault_root / "Sectors" / target_slug / "People.md"
    if not target_file.parent.exists():
        log.warning("views: sector dir %s doesn't exist; skipping People view", target_file.parent)
        return target_file

    body = _render_people_view(target_slug, people)
    atomic_write(target_file, body, vault_root=vault_root)
    return target_file


# ── Companies scan ────────────────────────────────────────────────────


def _scan_companies(vault_root: Path, target_slug: str) -> list[dict]:
    companies_dir = vault_root / "Companies"
    out: list[dict] = []
    if not companies_dir.is_dir():
        return out
    for f in sorted(companies_dir.iterdir()):
        if not f.is_file() or not f.name.endswith(".md"):
            continue
        try:
            meta = frontmatter.load(f).metadata or {}
        except Exception:
            continue
        if _slug_from_field(meta.get("sector")) != target_slug:
            continue
        bd_state = meta.get("bd_state")
        if not bd_state:
            continue
        out.append({
            "name": f.stem,
            "bd_state": str(bd_state),
            "bd_last_contact": str(meta.get("bd_last_contact") or ""),
            "bd_owner": str(meta.get("bd_owner") or ""),
            "bd_notes": str(meta.get("bd_notes") or "").split("\n")[0][:80],
        })
    return out


def _slug_from_field(field_value) -> str | None:
    if not field_value:
        return None
    s = str(field_value).lower()
    m = re.search(r"sectors/([a-z0-9-]+)", s)
    if m:
        return m.group(1)
    # F-21: canonical slugifier for the name-fallback (see from_bd._slug_from_field).
    from routines.sectors.schema import slugify_sector
    return slugify_sector(s)


def _render_bd_view(sector_slug: str, companies: list[dict]) -> str:
    today = date_cls.today().isoformat()
    out = [
        "---",
        "type: sector-view",
        "view_type: bd",
        f"sector: {sector_slug}",
        "memory_kind: semantic",
        "sensitivity: confidential",
        f"last_refreshed: {today}",
        "refreshed_by: routine:sectors-views",
        "generated_from: \"scan of Companies/*.md where sector == <slug> AND bd_state IS NOT NULL\"",
        "recall_priority: medium",
        "operator_locked: false",
        f"tags: [sector-view, bd, {sector_slug}, auto-generated]",
        "---",
        "",
        f"# {sector_slug.capitalize()} -- BD watch list",
        "",
        f"> **This file is auto-generated by `routines.sectors.views`.** Source of "
        "truth is the `bd_state` + `bd_last_contact` + `bd_owner` + `bd_notes` "
        "frontmatter on each `Companies/<X>.md`. Edit those files; the next "
        f"synthesis run refreshes this view (`last_refreshed: {today}`).",
        "",
        f"## Watch state at {today}",
        "",
    ]

    if not companies:
        out += [
            "| Company | State | Last contact | Owner | Notes |",
            "|---|---|---|---|---|",
            "| _(no companies in BD watch)_ | -- | -- | -- | Add `bd_state:` to a Company file to surface it here |",
        ]
    else:
        out += [
            "| Company | State | Last contact | Owner | Notes |",
            "|---|---|---|---|---|",
        ]
        # Sort by state then last contact desc
        STATE_ORDER = {"engaged": 0, "watching": 1, "won": 2, "dormant": 3, "lost": 4, "dead": 5}
        companies.sort(key=lambda c: (
            STATE_ORDER.get(c["bd_state"], 99),
            c["bd_last_contact"],
        ), reverse=False)
        for c in companies:
            notes = c["bd_notes"] or "_(none)_"
            out.append(
                f"| [[Companies/{c['name']}]] | `{c['bd_state']}` | "
                f"{c['bd_last_contact'] or '--'} | {c['bd_owner'] or '--'} | {notes} |"
            )

    out += [
        "",
        "## Watch state definitions",
        "",
        "| State | Meaning | Decay threshold |",
        "|---|---|---|",
        "| `watching` | Operator is tracking; not yet engaged in conversation | 180 days |",
        "| `engaged` | Active conversation; meetings + emails happening | 60 days |",
        "| `dormant` | Was engaged but gone quiet; not killed | 90 days |",
        "| `dead` | Confirmed no deal; archive context | n/a |",
        "| `won` | Mandate won; project active | n/a (sticky) |",
        "| `lost` | Mandate lost; competitor won | n/a (sticky) |",
        "",
        "Stale entries (last contact > threshold) are surfaced in the daily "
        "morning brief by the `bd-decay` routine.",
    ]
    return "\n".join(out)


# ── People scan ───────────────────────────────────────────────────────


def _scan_people(vault_root: Path, target_slug: str) -> list[dict]:
    people_dir = vault_root / "People"
    out: list[dict] = []
    if not people_dir.is_dir():
        return out
    for f in sorted(people_dir.iterdir()):
        if not f.is_file() or not f.name.endswith(".md"):
            continue
        try:
            meta = frontmatter.load(f).metadata or {}
        except Exception:
            continue
        sectors = meta.get("sectors")
        if not sectors:
            continue
        # Normalize to list of slugs
        if isinstance(sectors, str):
            sectors = [sectors]
        sector_slugs = {str(s).lower().replace(" ", "-") for s in sectors}
        if target_slug not in sector_slugs:
            continue
        out.append({
            "name": f.stem,
            "firm": _resolve_firm(meta.get("firm")),
            "role": str(meta.get("role") or "").strip(),
            "significance": str(meta.get("significance") or meta.get("tldr") or "").strip(),
        })
    return out


def _resolve_firm(field_value) -> str:
    if not field_value:
        return "--"
    s = str(field_value)
    m = re.search(r"\[\[Companies/([^\]]+?)\]\]", s)
    return m.group(1) if m else s


def _render_people_view(sector_slug: str, people: list[dict]) -> str:
    today = date_cls.today().isoformat()
    out = [
        "---",
        "type: sector-view",
        "view_type: people",
        f"sector: {sector_slug}",
        "memory_kind: semantic",
        "sensitivity: internal",
        f"last_refreshed: {today}",
        "refreshed_by: routine:sectors-views",
        "generated_from: \"scan of People/*.md where '<slug>' in sectors[]\"",
        "recall_priority: medium",
        "operator_locked: false",
        f"tags: [sector-view, people, {sector_slug}, auto-generated]",
        "---",
        "",
        f"# {sector_slug.capitalize()} -- sector people",
        "",
        f"> **This file is auto-generated by `routines.sectors.views`.** Source "
        "of truth is the `sectors:` list in each `People/<Name>.md` frontmatter.",
        "",
        f"## People at {today}",
        "",
    ]

    if not people:
        out += [
            "_(no people tagged with this sector)_",
            "",
            "Add `sectors: [<slug>]` to a `People/<Name>.md` to surface them here.",
        ]
    else:
        out += [
            "| Person | Firm | Role | Significance |",
            "|---|---|---|---|",
        ]
        for p in people:
            sig = p["significance"][:100] if p["significance"] else "--"
            out.append(
                f"| [[People/{p['name']}]] | {p['firm']} | {p['role'] or '--'} | {sig} |"
            )

    return "\n".join(out)
