"""Render and atomic-write sector-extraction proposals.

Each run produces ONE proposal file per sector at:
    Routines/sector-extraction/<date>-<sector>.md

with `status: pending-review`. Operator applies via REVIEW chip; the
applied extracts then flow (via Phase 4 synthesizer's read pass) into
`Sectors/<X>/_sources/from-*.md` provenance files.
"""

from __future__ import annotations

from datetime import date as date_cls
from pathlib import Path

from routines.sectors.schema import SectorProposal
from routines.shared.vault_writer import atomic_write


def proposal_path(vault_root: Path, sector: str, the_date: date_cls) -> Path:
    return (vault_root / "Routines" / "sector-extraction"
            / f"{the_date.isoformat()}-{sector}.md")


def write_proposal(vault_root: Path, doc: SectorProposal, the_date: date_cls) -> Path:
    path = proposal_path(vault_root, doc.sector, the_date)
    atomic_write(path, render_markdown(doc, the_date), vault_root=vault_root)
    return path


def render_markdown(doc: SectorProposal, the_date: date_cls) -> str:
    date_str = the_date.isoformat()
    sector = doc.sector
    out: list[str] = [
        "---",
        "type: sector-extraction-proposal",
        f"sector: {sector}",
        "sensitivity: confidential",
        f"date: {date_str}",
        f"generated_at: {doc.generated_at.isoformat()}",
        f"run_id: {doc.run_id}",
        f"source_types_run: {doc.source_types_run}",
        f"inputs_scanned: {doc.inputs_scanned}",
        f"inputs_matched: {doc.inputs_matched}",
        f"extracts: {doc.extract_count}",
        "status: pending-review",
        f"tags: [sector-extraction, {sector}, routines, proposal]",
        "---",
        "",
        f"# Sector extraction proposal — {sector} · {date_str}",
        "",
        (
            f"Walked vault inputs (source types: {', '.join(doc.source_types_run)}) "
            f"and identified **{doc.extract_count} extract(s)** for review. "
            f"**Nothing is auto-applied** — review, edit, and apply via the "
            f"REVIEW chip on the dashboard. Applied extracts append to "
            f"`Sectors/{sector}/_sources/from-<source-type>.md` provenance files; "
            f"the next `sector-synthesize` run reads from there."
        ),
        "",
        f"_Inputs scanned: {doc.inputs_scanned}; matched: {doc.inputs_matched}._",
        "",
    ]

    if doc.skipped_reasons:
        out += ["**Skipped:**"]
        for reason, count in sorted(doc.skipped_reasons.items()):
            out.append(f"- {reason}: {count}")
        out.append("")

    out += [
        "## Operator action",
        "",
        "1. Review each extract below.",
        "2. For each accept, the operator copies the extract block (frontmatter + bullets) "
        f"into the relevant `Sectors/{sector}/_sources/from-<source-type>.md` file.",
        "3. Update this proposal's frontmatter `status:` to `applied` or `rejected` once handled.",
        "4. Next `sector-synthesize` run (Sat 02:30) reads the applied provenance + redrafts claim files.",
        "",
        "---",
        "",
    ]

    if not doc.extracts:
        out += [
            "_No extracts surfaced this run. Could mean:_",
            "- No matching inputs for this sector in scanning window",
            "- All matching inputs already have `last_sector_extract:` stamps current",
            "- Routine ran with `--skip-llm` and keyword filter found no matches",
        ]
        return "\n".join(out)

    # Group extracts by source_type for readable display
    by_type: dict[str, list] = {}
    for ex in doc.extracts:
        by_type.setdefault(ex.source_type, []).append(ex)

    for source_type in sorted(by_type.keys()):
        type_extracts = by_type[source_type]
        out += [
            f"## from-{source_type} ({len(type_extracts)} extract(s))",
            "",
        ]
        for i, ex in enumerate(type_extracts, 1):
            out += [
                f"### {i}. From `{ex.source_path}`",
                "",
                f"- **source_root:** `{ex.source_root}` (weight: {ex.weight()})",
                f"- **claim_targets:** {', '.join(ex.claim_targets)}",
                f"- **subsectors:** {ex.subsectors}",
                f"- **sensitivity:** {ex.sensitivity}",
            ]
            if ex.confidence_hint:
                out.append(f"- **operator_confidence_hint:** {ex.confidence_hint}")
            out += ["", "**Bullets:**", ""]
            for b in ex.bullets:
                out.append(f"- {b}")
            out += ["", "---", ""]

    out += [
        "",
        "_Generated by `routines.sectors.extract` — fully local. "
        f"Run-id: {doc.run_id}._",
    ]
    return "\n".join(out)
