"""Render scan results as a markdown proposal for operator review.

Output goes to `Routines/memory-promotion/<date>-<project>.md`. Operator reads,
edits if needed, then either ignores it (status quo) or runs `memory-promote
apply <run-id>` to enact specific items. **Never auto-applies.**
"""

from __future__ import annotations

from datetime import date
from typing import Any

from routines.promotion.scan import ProjectScan
from routines.shared.vault_writer import serialise_note


def render_proposal(scan: ProjectScan, *, run_id: str) -> str:
    """Build the markdown proposal for one project's scan."""
    metadata: dict[str, Any] = {
        "type": "promotion-proposal",
        "project": f"[[Projects/{scan.project}]]",
        "date": date.today().isoformat(),
        "sensitivity": "internal",
        "status": "proposed",
        "run-id": run_id,
        "tags": ["routine", "memory-promotion", "proposal"],
        "tldr": (
            f"{len(scan.duplicate_decisions)} duplicate decision(s), "
            f"{len(scan.stale_actions)} stale open action(s), "
            f"{len(scan.lesson_candidates)} lesson candidate(s) for review."
        ),
    }

    parts: list[str] = [
        f"# Memory promotion proposal — {scan.project}",
        "",
        "> Read through the items below. Each is a **proposal**, not an applied change. "
        "To enact an item, edit the relevant note manually OR run `memory-promote apply` "
        "(once that subcommand ships) targeting specific item IDs.",
        "",
    ]

    if scan.is_empty:
        parts.append("**Nothing to promote or compact.** Project memory is in good shape.")
        return serialise_note(metadata, "\n".join(parts))

    if scan.duplicate_decisions:
        parts += ["## Duplicate decisions", ""]
        for i, d in enumerate(scan.duplicate_decisions, 1):
            parts.append(f"### D-{i}. {d.decision_text}")
            parts.append("Appears in:")
            for s in d.sources:
                parts.append(f"- [[{s.removesuffix('.md')}]]")
            parts.append("")
            parts.append("**Suggested action:** consolidate to a single canonical entry "
                         f"in `Projects/{scan.project}/09 Decision Log.md` if not already; "
                         "remove duplicates from meeting notes (those should reference, not restate).")
            parts.append("")

    if scan.stale_actions:
        parts += ["## Stale open actions", ""]
        # Group by note_path for readability
        by_note: dict[str, list] = {}
        for a in scan.stale_actions:
            by_note.setdefault(a.note_path, []).append(a)
        for note_path, actions in by_note.items():
            parts.append(f"### From [[{note_path.removesuffix('.md')}]]")
            for a in actions:
                parts.append(f"- `[ ] {a.action_text}` — open for **{a.days_stale} days**")
            parts.append("")
            parts.append("**Suggested action:** mark as ✅ done, ❌ dropped, or ⏸ blocked, "
                         "or move to a current sprint note. Open `[ ]` checkboxes >30 days are noise.")
            parts.append("")

    if scan.lesson_candidates:
        parts += ["## Lesson candidates", ""]
        parts.append("These bullets in `Lessons Learned` look ready to promote to "
                     "`Registers/Lessons.md` (cross-project register). Review for whether "
                     "they're genuinely cross-cutting or remain project-specific.")
        parts.append("")
        for i, l in enumerate(scan.lesson_candidates, 1):
            parts.append(f"### L-{i}. {l.pattern_text}")
            parts.append(f"From: [[{l.note_path.removesuffix('.md')}]]")
            parts.append("")
            parts.append("**Suggested action:** if cross-cutting, append a new entry under "
                         "`Registers/Lessons.md` with a stable `lesson-id` header.")
            parts.append("")

    parts.append("---")
    parts.append(f"*Proposal generated by `memory-promote` — run-id `{run_id}`.*")

    return serialise_note(metadata, "\n".join(parts))
