"""Markdown writer — InsightProposal → ``Routines/system-insights/*.md``.

Output frontmatter shape (load-bearing):

  type: system-insight
  kind: system-insight       # post-#58 — resolves to "approval" tier
  status: pending-review     # pending-review picked up by the scanner
  date: YYYY-MM-DD
  week: YYYY-WNN
  observation: <one-line>
  suggested_action: <one-line>
  evidence_count: <int>
  evidence_window_days: 7

Idempotency contract:
  * Same ``(week, topic_slug)`` re-run → file already exists.
  * If its frontmatter ``status`` is still ``pending-review``, overwrite
    in place (the new analysis may have refined the evidence).
  * If its frontmatter ``status`` has progressed past ``pending-review``
    (operator routed / rejected / requested revision / marked applied),
    skip the write — the operator has already triaged it; don't stomp.

Returns the path written (or ``None`` if skipped).
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import frontmatter

from routines.learning.system_insights.analyse import InsightProposal

log = logging.getLogger(__name__)


PROPOSAL_DIR_REL = "Routines/system-insights"
SKIP_STATUSES = {"applied", "rejected", "routed", "revision-requested"}


def proposal_path_for(
    vault_root: Path, proposal: InsightProposal,
) -> Path:
    """``<vault>/Routines/system-insights/<YYYY-WNN>-<topic-slug>.md``."""
    filename = f"{proposal.week}-{proposal.topic_slug}.md"
    return vault_root / PROPOSAL_DIR_REL / filename


def _render_body(proposal: InsightProposal, *, now: datetime) -> str:
    lines: list[str] = []
    lines.append(f"# {proposal.observation}")
    lines.append("")

    lines.append("## Observation")
    lines.append("")
    lines.append(proposal.observation)
    lines.append("")

    if proposal.evidence_sample:
        shown = len(proposal.evidence_sample)
        lines.append(f"## Evidence sample ({shown} of {proposal.evidence_count})")
        lines.append("")
        for entry in proposal.evidence_sample:
            payload = json.dumps(entry, default=str, sort_keys=True)
            lines.append(f"- `{payload}`")
        lines.append("")

    lines.append("## Suggested action")
    lines.append("")
    lines.append(proposal.suggested_action)
    lines.append("")

    if proposal.source_query:
        lines.append("## Source query (operator can re-run to verify)")
        lines.append("")
        lines.append("```")
        lines.append(proposal.source_query)
        lines.append("```")
        lines.append("")

    ts_str = now.strftime("%Y-%m-%d %H:%M %Z").strip()
    lines.append(
        f"*Generated by `routines.learning.system_insights` on {ts_str}.*"
    )
    lines.append(
        "*Routes through standard proposals lifecycle (#8 + #58). "
        "Review and Route / Reject / Skip / Request revision as appropriate.*"
    )
    return "\n".join(lines) + "\n"


def write_proposal(
    vault_root: Path,
    proposal: InsightProposal,
    *,
    now: Optional[datetime] = None,
) -> Optional[Path]:
    """Render + persist a proposal. Returns the path written or None when skipped.

    Idempotency: re-runs in the same week overwrite the pending-review
    file in place (refining evidence is welcome); proposals the operator
    has already triaged (status in ``SKIP_STATUSES``) are left untouched.
    """
    now = now or datetime.now(timezone.utc)
    path = proposal_path_for(vault_root, proposal)

    if path.is_file():
        try:
            existing = frontmatter.load(path)
            status = str(existing.metadata.get("status") or "").strip().lower()
            if status in SKIP_STATUSES:
                log.info(
                    "system_insights: skipping write to %s — operator-triaged "
                    "status=%r", path, status,
                )
                return None
        except Exception as e:  # noqa: BLE001
            log.warning(
                "system_insights: failed to parse existing %s (%s) — "
                "overwriting", path, e,
            )

    post = frontmatter.Post(_render_body(proposal, now=now))
    post.metadata["type"] = "system-insight"
    post.metadata["kind"] = "system-insight"
    post.metadata["status"] = "pending-review"
    post.metadata["date"] = now.date().isoformat()
    post.metadata["week"] = proposal.week
    post.metadata["observation"] = proposal.observation
    post.metadata["suggested_action"] = proposal.suggested_action
    post.metadata["evidence_count"] = proposal.evidence_count
    post.metadata["evidence_window_days"] = proposal.evidence_window_days

    path.parent.mkdir(parents=True, exist_ok=True)
    serialised = frontmatter.dumps(post) + "\n"
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(serialised, encoding="utf-8")
    tmp.replace(path)
    log.info("system_insights: wrote proposal %s", path)
    return path


__all__ = [
    "PROPOSAL_DIR_REL",
    "SKIP_STATUSES",
    "proposal_path_for",
    "write_proposal",
]
